# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc 'Bump build numbers, and set the version to match the pacakage.json version.'
  lane :bump do
    package = load_json(json_path: "../package.json")
    increment_build_number(
      xcodeproj: './homeplanner.xcodeproj'
    )
    increment_version_number(
      xcodeproj: './homeplanner.xcodeproj',
      version_number: package['version']
    )
  end
end
