# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc 'Bump build number and set the version to match the package.json version.'
  lane :bump do
    package = load_json(json_path: "../package.json")
    increment_version_code(
      gradle_file_path: "./app/build.gradle",
    )
    increment_version_name(
      gradle_file_path: "./app/build.gradle",
      version_name: package['version']
    )
  end

  desc "Send build to Firebase App Distribution for testing"
  lane :distribute_internal do
      build_android_app(
        task: "bundle",
        build_type: 'Release'
      )
      json_data = load_json(json_path: './app/google-services.json')
      mobilesdk_app_id = json_data["client"][0]["client_info"]["mobilesdk_app_id"]
      release = firebase_app_distribution(
          app: mobilesdk_app_id,
          groups: "testers",
          android_artifact_type: "AAB",
          service_credentials_file: "../fastlane/secrets/firebase_app_distribution_service_account.json"
      )
  end

  # desc "Runs all the tests"
  # lane :test do
  #   gradle(task: "test")
  # end

  # desc "Submit a new Beta Build to Crashlytics Beta"
  # lane :beta do
  #   gradle(task: "clean assembleRelease")
  #   crashlytics
  
  #   # sh "your_script.sh"
  #   # You can also use other beta testing services here
  # end

  # desc "Deploy a new version to the Google Play"
  # lane :deploy do
  #   gradle(task: "clean assembleRelease")
  #   upload_to_play_store
  # end
end
