name: Build React Native Android

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      # Add environment variables for Android build tools
      JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64
      ANDROID_SDK_ROOT: /usr/local/lib/android/sdk

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21'

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn install

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 34
          build-tools: 34.0.0

      - name: Create .env file
        run: |
          echo "RN_API_URL=${{ secrets.RN_API_URL }}" > .env
          echo "RN_BUG_TICKET_ID=${{ secrets.RN_BUG_TICKET_ID }}" >> .env
          echo "RN_BUG_TICKET_SECRET=${{ secrets.RN_BUG_TICKET_SECRET }}" > .env
          echo "RN_GOOGLE_CLIENT_ID=${{ secrets.RN_GOOGLE_CLIENT_ID }}" >> .env

      - name: Decode keystore
        run: |
          echo ${{ secrets.ANDROID_KEYSTORE }} | base64 --decode > android/app/Production.keystore

      - name: Place google-services.json
        run: |
          echo ${{ secrets.GOOGLE_SERVICES_JSON }} | base64 --decode > android/app/google-services.json

      - name: Build APK
        run: |
          cd android
          ./gradlew assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/app-release.apk
